project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true



